__default__:
  jobname: "{rule}.{wildcards}"
  nodes: 1
  ntaskspernode: 1
  cpuspertask: 1
  mem: "1000mb"
  time: "5:00"
  account: "ACCOUNT"
  partition: "standard"
  mailuser: "EMAIL"
  mailtype: "BEGIN,END,FAIL"
  output: "code/log/%x-%j.out"

count_words:
  cpuspertask: 2
  mem: "2000mb"
  time: "10:00"
